[profile.release]
lto = true
strip = true
opt-level = "z"
panic = "abort"

[workspace.package]
version = "0.1.0"
authors = ["void-ripper"]
edition = "2021"

[workspace]
resolver = "2"
members = ["tarantula-daemon", "tarantula-scrapper"]
